Veil: src/veil_datatypes.c File Reference
veil_datatypes.c File Reference
Code for non-bitmap datatypes.
#include "postgres.h"
#include "veil_datatypes.h"
#include "veil_funcs.h"
Functions
Range * vl_NewRange (bool shared)
Create a new session or shared Range object.
Int4Var * vl_NewInt4 (bool shared)
Create a new session or shared Int4Var object.
Detailed Description
Code for non-bitmap datatypes.
Author:       Marc Munro
Copyright (c) 2005 - 2011 Marc Munro
License:      BSD
Definition in file veil_datatypes.c.
Function Documentation
vl_NewRange()
Range* vl_NewRange (bool shared)
Create a new session or shared Range object.
Parameters
shared Whether the object is to be created in shared (true) or session (false) memory.
Returns
Pointer to newly created object.
Definition at line 28 of file veil_datatypes.c.
References Range::type, vl_malloc(), and vl_shmalloc().
vl_NewInt4()
Int4Var* vl_NewInt4 (bool shared)
Create a new session or shared Int4Var object.
Parameters
shared Whether the object is to be created in shared (true) or session (false) memory.
Returns
Pointer to newly created object.
Definition at line 52 of file veil_datatypes.c.
References Int4Var::type, vl_malloc(), and vl_shmalloc().