Veil: src/veil_utils.c File Reference
veil_utils.c File Reference
Miscelaneous functions for veil.
#include "postgres.h"
#include "utils/memutils.h"
#include "veil_funcs.h"
#include "veil_datatypes.h"
Functions
void * vl_malloc (size_t size)
Dynamically allocate memory using palloc in TopMemoryContext.
char * vl_ObjTypeName (ObjType obj)
Return a static string describing an ObjType object.
Detailed Description
Miscelaneous functions for veil.
Author:       Marc Munro
Copyright (c) 2005 - 2011 Marc Munro
License:      BSD
Definition in file veil_utils.c.
Function Documentation
vl_malloc()
void* vl_malloc (size_t size)
Dynamically allocate memory using palloc in TopMemoryContext.
Parameters
size The size of the chunk of memory being requested.
Returns
Pointer to the newly allocated chunk of memory
Definition at line 28 of file veil_utils.c.
Referenced by create_shared_hash(), get_shmem_context(), vl_NewBitmap(), vl_NewBitmapArray(), vl_NewInt4(), vl_NewInt4Array(), and vl_NewRange().
vl_ObjTypeName()
char* vl_ObjTypeName (ObjType obj)
Return a static string describing an ObjType object.
Parameters
obj The ObjType for which we want a description.
Returns
Pointer to a static string describing obj.
Definition at line 45 of file veil_utils.c.
Referenced by vl_next_variable(), and vl_type_mismatch().